gridCRUD/gridCRUD/urls.py
from django.contrib import admin
from django.urls import path

from cridApp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('addnew', views.addnew),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

gridCRUD/cridApp/models.py
from django.db import models

class Employer(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact = models.CharField(max_length=15)

    class Meta:
        db_table = 'employee'
# Create your models here.

gridCRUD/cridApp/forms.py
from django import forms
from cridApp.models import Employer

class EmployerForm(forms.ModelForm):
    class Meta:
        model = Employer
        fields = ['name', 'contact', 'email']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'contact': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),

        }

gridCRUD/cridApp/views.py
from  .forms import EmployerForm
from django.shortcuts import render, redirect
from .models import Employer

def addnew(request):
    if request.method =="POST":
        form = EmployerForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/')
            except:
                pass
    else:
        form = EmployerForm()
    return render(request, 'cridApp/index.html', {'form': form})

def index(request):
    employees= Employer.objects.all()
    return render (request, 'cridApp/show.html', {'employees': employees})

def edit(request, id):
    employees= Employer.objects.get(id=id)
    return render(request, 'cridApp/edit.html', {'employees': employees})

def update(request, id):
    employees = Employer.objects.get(id=id)
    form = EmployerForm(request.POST, instance=employees)
    if form.is_valid():
        form.save()
        return redirect("/")
    return render(request, 'cridApp/edit.html', {'employees': employees})

def destroy(request, id):
    employee = Employer.objects.get(id=id)
    employee.delete()
    return redirect("/")




# Create your views here.

gridCRUD/cridApp/templates/cridApp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}

    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet"
          id="bootstrap-css">
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
</head>


<body>
<div class="container">
    <div class="row">
    {% block content %}{% endblock %}
    </div>
</div>


<script>
    $(document).ready(function () {
        $('#bootstrapdatatable').DataTable({
                "aLengthMenu": [[3, 5, 10, 25, -1], [3, 5, 10, 25, "All"]],
                "iDisplayLength": 3
            }
        );
    });
</script>
</body>
</html>

gridCRUD/cridApp/templates/cridApp/edit.html
{% extends "cridApp/base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
    <div class="col-md-12">
    <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4>
    <form method="POST" class="post-form" action="/update/{{ employee.id }}">
        {% csrf_token %}
        <div class="container">
            <br>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Update Details</h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Id:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="id" id="id_id" required maxlength="20"
                           value="{{ employee.id }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Name:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="name" id="id_name" required maxlength="100"
                           value="{{ employee.name }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Email:</label>
                <div class="col-sm-4">
                    <input type="email" class="form-control" name="email" id="id_email" required maxlength="254"
                           value="{{ employee.email }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Employee Contact:</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="contact" id="id_contact" required maxlength="15"
                           value="{{ employee.contact }}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-1 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success btn-lg">Update</button>
                </div>
            </div>
        </div>
    </form>
    </div>


{% endblock content %}

gridCRUD/cridApp/templates/cridApp/index.html
{% extends "cridApp/base.html" %}

{% block title %}Add New Employee Records{% endblock title %}

{% block content %}
    <div class="col-md-12">
        <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4>

        <form method="POST" class="post-form" action="/addnew">
            {% csrf_token %}
            <div class="container">
                <br>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Enter Details</h3>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Name:</label>
                    <div class="col-sm-4">
                        {{ form.name }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Email:</label>
                    <div class="col-sm-4">
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Employee Contact:</label>
                    <div class="col-sm-4">
                        {{ form.contact }}
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-1 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

gridCRUD/cridApp/templates/cridApp/show.html
{% extends "cridApp/base.html" %}

{% block title %}Employee Records{% endblock title %}

{% block content %}
 <div class="col-md-12">
        <h4>Django CRUD (Create Read Update Delete) Example - Bootstrap Datatable GRID</h4> <span><a href="/addnew" class="btn btn-primary">Add New Record</a></span>
        <div class="table-responsive">
  <table id="bootstrapdatatable" class="table table-striped table-bordered" width="100%">
            <thead>
                <th><input type="checkbox" id="checkall" /></th>
                <th>ID</th>
                <th>Employee Name</th>
                <th>Employee Email</th>
                <th>Employee Contact</th>
                <th>Edit</th>
                <th>Delete</th>
             </thead>
   <tbody>
   {% for employee in employees %}
    <tr>
     <td><input type="checkbox" class="checkthis" /></td>
     <td>{{ employee.id }}</td>
     <td>{{ employee.name }}</td>
     <td>{{ employee.email }}</td>
     <td>{{ employee.contact }}</td>
     <td><p data-placement="top" data-toggle="tooltip" title="Edit"><a href="/edit/{{ employee.id }}" class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" ><span class="glyphicon glyphicon-pencil"></span></a></p></td>
     <td><p data-placement="top" data-toggle="tooltip" title="Delete"><a href="/delete/{{ employee.id }}" class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></a></p></td>
    </tr>
   {% endfor %}
   </tbody>

  </table>
        </div>
    </div>
{% endblock content %}